# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "bce65271466736f3e6c5450e8b38a9c1"
application_url = "https://finer-repeatedly-giraffe.ngrok-free.app"
embedded = true
name = "ds-task-export-orders"
handle = "ds-task-export-orders"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_orders,read_customers"

[auth]
redirect_urls = [
  "https://finer-repeatedly-giraffe.ngrok-free.app/auth/callback",
  "https://finer-repeatedly-giraffe.ngrok-free.app/auth/shopify/callback",
  "https://finer-repeatedly-giraffe.ngrok-free.app/api/auth/callback"
]

[pos]
embedded = false
